name: slides
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.12.2
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - click=8.1.7
  - expat=2.5.0
  - flask=2.2.5
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=73.1
  - itsdangerous=2.0.1
  - jinja2=3.1.3
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libcurl=8.5.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgd=2.3.3
  - libglib=2.78.4
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - librsvg=2.54.4
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - openjpeg=2.3.0
  - openssl=3.0.13
  - pango=1.50.7
  - pcre2=10.42
  - pip=23.3.1
  - pixman=0.40.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - python=3.12.2
  - readline=8.2
  - setuptools=68.2.2
  - soupsieve=2.5
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - werkzeug=2.3.8
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - flask-jsglue==0.3.1
      - python-markdown-math==0.8
